// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAULNOEjyu5EMy1xVimQG9LlEAh__WS2nA',
    appId: '1:104240505555:web:2f0ad35aa3e665c953ea26',
    messagingSenderId: '104240505555',
    projectId: 'graduation-project-cbc74',
    authDomain: 'graduation-project-cbc74.firebaseapp.com',
    databaseURL: 'https://graduation-project-cbc74-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'graduation-project-cbc74.appspot.com',
    measurementId: 'G-ZB0998E2P5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRqz4AnuVuOsZvN0iXLWRBp5qdzNT3Vpg',
    appId: '1:104240505555:android:e56a52d60b4a69cd53ea26',
    messagingSenderId: '104240505555',
    projectId: 'graduation-project-cbc74',
    databaseURL: 'https://graduation-project-cbc74-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'graduation-project-cbc74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3cIsIGe6-Zgpt_0weiQ_YhRjjKV7Z6hU',
    appId: '1:104240505555:ios:60f21cfe1c8ad8e653ea26',
    messagingSenderId: '104240505555',
    projectId: 'graduation-project-cbc74',
    databaseURL: 'https://graduation-project-cbc74-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'graduation-project-cbc74.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3cIsIGe6-Zgpt_0weiQ_YhRjjKV7Z6hU',
    appId: '1:104240505555:ios:60f21cfe1c8ad8e653ea26',
    messagingSenderId: '104240505555',
    projectId: 'graduation-project-cbc74',
    databaseURL: 'https://graduation-project-cbc74-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'graduation-project-cbc74.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAULNOEjyu5EMy1xVimQG9LlEAh__WS2nA',
    appId: '1:104240505555:web:ef5024cf2e1fc16853ea26',
    messagingSenderId: '104240505555',
    projectId: 'graduation-project-cbc74',
    authDomain: 'graduation-project-cbc74.firebaseapp.com',
    databaseURL: 'https://graduation-project-cbc74-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'graduation-project-cbc74.appspot.com',
    measurementId: 'G-B21EBD51HK',
  );
}
