name: graduation_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  #responsive
  flutter_screenutil: ^5.7.0

  #di
  get_it: ^7.6.0

  #state
  provider: ^6.1.1

  #navigation
  go_router: ^9.0.3

  #functional programing
  dartz: ^0.10.1

flutter:
  uses-material-design: true
